version: '3.8'
services:
  node000ex1:
    image: node:lts-buster
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/next_app
    command: npm run dev
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

